= Security scanner reports for automation testing

The project’s primary objective is to provide a set of security scanner report samples to ensure proper report processing in any downstream automation.

== Locating report samples

Please navigate to the https://github.com/samoylenko/report-samples/tree/reports[`reports`] branch.

=== SAST, SCA, and Container Image report samples

There are two primary report types:

. Container image scan reports in the `reports/image-reports` directory
. SAST/SCA report samples in individual project directories

=== Compiled code

Many static scanners require build artifacts, in addition to code, to run correctly.
So we currently push, but do not store compiled samples due to their size.
These samples are saved in tgz format to preserve any file system flags and can be used in scanner automation testing as well.

== Scanners

Currently used scanners:

. https://github.com/anchore/grype[Anchore Grype]
. https://github.com/aquasecurity/trivy[Aqua Security Trivy]
. https://docker.com/products/docker-scout[Docker Scout]
. https://snyk.io[Snyk]

== Projects

Currently used projects that have both SAST/SCA and Container Image scan report samples:

. https://github.com/OWASP-Benchmark/BenchmarkJava[OWASP Benchmark (Java)]
. https://github.com/juice-shop/juice-shop[OWASP Juice Shop]
. https://github.com/kaakaww/javaspringvulny[kaakaww/javaspringvulny]
. https://github.com/samoylenko/vulnerable-app-nodejs-express[samoylenko/vulnerable-app-nodejs-express]

Additionally, the list of random images in the xref:image-list.txt[`image-list.txt`] file.
These only have corresponding image scan reports available.
